services:
  postgres:
    image: postgres:16-alpine
    container_name: muzo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

  web-api:
    build: ./backend
    container_name: muzo-web-api
    depends_on:
      - postgres
      - keycloak
      - opensearch
      - grafana
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}

      KC_URL: http://keycloak:8080
      KC_PUBLIC_URL: $(KEYCLOAK_PUBLIC_URL)
      KC_REALM: ${KEYCLOAK_REALM}
      KC_CLIENT_ID: ${muzo-client}
      KC_REDIRECT_URI: ${KEYCLOAK_REDIRECT_URI}
      SECRET_KEY: ${SECRET_KEY}

      OPENSEARCH_URL: http://opensearch:9200

      TIMEZONE: ${TIMEZONE}

      UPLOADS_PATH: /data/uploads
      AUDIO_PATH: /data/audio

      STREAMING_URL: ${STREAMING_PUBLIC_URL}
      STREAM_SECRET: ${STREAM_SECRET}
      STREAMING_URL_TTL: ${STREAMING_URL_TTL}

      GRAFANA_URL: ${GRAFANA_PUBLIC_URL}
      GRAFANA_DASHBOARD: ${GRAFANA_DASHBOARD}
    ports:
      - "${WEB_PORT}:5000"
    volumes:
      - ./backend:/app
      - ./images_data:/data/uploads
      - ./audio_data:/data/audio

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    container_name: muzo-keycloak
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak-config:/opt/keycloak/data/import
    ports:
      - "${KEYCLOAK_PORT}:8080"

  streaming:
    build: ./streaming
    environment:
      AUDIO_PATH: /audio_data
      STREAM_SECRET: ${STREAM_SECRET}
    container_name: muzo-streaming
    ports:
      - "${STREAMING_PORT}:5000"
    volumes:
      - ./audio_data:/audio_data

  opensearch:
    image: opensearchproject/opensearch:3
    container_name: muzo-search
    restart: unless-stopped
    environment:
      discovery.type: single-node
      DISABLE_SECURITY_PLUGIN: true
      OPENSEARCH_JAVA_OPTS: -Xms512m -Xmx512m
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: ${OPENSEARCH_ADMIN_PASSWORD}
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    ports:
      - "9200:9200"

  grafana:
    image: grafana/grafana:latest
    container_name: muzo-grafana
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_USERS_ALLOW_SIGNUP: "false"
      GF_SECURITY_ALLOW_EMBEDDING: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Viewer"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    restart: unless-stopped
    depends_on:
      - postgres


volumes:
  postgres_data:
    driver: local
  keycloak_data:
    driver: local
  images_data:
    driver: local
  audio_data:
    driver: local
  opensearch_data:
    driver: local
  grafana_data:
    driver: local
