services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: muzo
      POSTGRES_PASSWORD: muzo
      POSTGRES_DB: muzodb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

  web-api:
    image: muzo-web
    depends_on:
      - postgres
      - keycloak
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: muzodb
      DB_USER: muzo
      DB_PASSWORD: muzo

      KC_URL: http://keycloak:8080
      KC_PUBLIC_URL: http://localhost:8080
      KC_REALM: muzo-realm
      KC_CLIENT_ID: muzo-client
      KC_REDIRECT_URI: http://localhost:5000/callback
      SECRET_KEY: topsecretkey

      TIMEZONE: Europe/Bucharest
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak-config:/opt/keycloak/data/import
    ports:
      - "8080:8080"

volumes:
  postgres_data:
  keycloak_data: