apiVersion: 1

datasources:
  - name: Postgres-Muzo
    uid: postgres-muzo
    type: postgres
    url: postgres:5432
    user: muzo
    secureJsonData:
      password: muzo
    jsonData:
      database: muzodb
      sslmode: 'disable'
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
